/*
  $Id: ejp_tracer_TracerAPI.h,v 1.5 2005/02/14 12:59:49 vauclair Exp $

  Copyright (C) 2002-2005 Sebastien Vauclair

  This file is part of Extensible Java Profiler.

  Extensible Java Profiler is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  Extensible Java Profiler is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with Extensible Java Profiler; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ejp_tracer_TracerAPI */

#ifndef _Included_ejp_tracer_TracerAPI
#define _Included_ejp_tracer_TracerAPI
#ifdef __cplusplus
extern "C" {
#endif
  /* Inaccessible static: error */
  /*
   * Class:     ejp_tracer_TracerAPI
   * Method:    nativeEnableTracing
   * Signature: ()V
   */
  JNIEXPORT void JNICALL Java_ejp_tracer_TracerAPI_nativeEnableTracing
  (JNIEnv *, jclass);

  /*
   * Class:     ejp_tracer_TracerAPI
   * Method:    nativeDisableTracing
   * Signature: ()V
   */
  JNIEXPORT void JNICALL Java_ejp_tracer_TracerAPI_nativeDisableTracing
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
